sudo: required
dist: trusty
language: c
compiler:
  - gcc
  - clang
# Change this to your needs


addons:
  apt:
    sources:
    packages:
      - python3
      - libcfitsio3-dev
      - libhdf5-dev # in newer releases
        #- libhdf5-serial-dev #on precise


script:
  - ./configure --disable-jbig && make
  - cd dv_tests
  #- export LD_LIBRARY_PATH=../.libs/
  - sudo make install
  #- ./run_tests.py -d ../.libs/davinci -t .
  - ./run_tests.py -t .

